module.exports = {
    attachEvent: require('./attach-event'),
    clearSlashes: require('./clear-slashes'),
    DataForm: require('./data-form'),
    dictToQueryString: require('./dict-to-query-string'),
    dictToStringJSON: require('./dict-to-string-json'),
    each: require('./each'),
    execGenerator: require('./exec-generator'),
    file: require('./file'),
    generatePassword: require('./generate-password'),
    getComponent: require('./get-component'),
    isArray: require('./is-array'),
    isClass: require('./is-class'),
    isElement: require('./is-element'),
    isFunction: require('./is-function'),
    isIterator: require('./is-iterator'),
    isNode: require('./is-node'),
    isNumber: require('./is-number'),
    isObject: require('./is-object'),
    isString: require('./is-string'),
    parseQueryString: require('./parse-query-string'),
    removeEvent: require('./remove-event'),
    resolvePath: require('./resolve-path'),
    toJSON: require('./to-json'),
    unique: require('./unique')
};